name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: Darkstar085/VuePagesAction@2.0.0
      with:
        username: 'SuperiorOS-Devices'
        reponame: 'SuperiorOS-Devices.github.io'
        token: ${{ secrets.GH_TOKEN }}
        gitemail: ${{ secrets.GH_MAIL }}
        gitname: ${{ secrets.GH_USERNAME }}
        cname: 'downloads.superioros.org'
        
